# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-22 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_session_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='session_keys',
        ),
    ]
